services:
  adservice:
    image: adservice
    environment:
      - PORT=9555

  productcatalogservice:
    image: productcatalogservice
    environment:
      - PORT=3550
      - DISABLE_PROFILER=1

  cartservice:
    image: cartservice
    environment:
      - REDIS_ADDR=redis-cart:6379
    depends_on:
      - redis-cart

  redis-cart:
    image: redis:6-alpine

  shippingservice:
    image: shippingservice
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1

  currencyservice:
    image: currencyservice
    environment:
      - PORT=7000
      - DISABLE_PROFILER=1

  paymentservice:
    image: paymentservice
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1

  emailservice:
    image: emailservice
    environment:
      - PORT=8080
      - DISABLE_PROFILER=1
